### ISSUE TITLE
Readme.md 작성

### ISSUE THREAD

**Issue by jeonghoonkang** [jhyun0919/EnergyData_jhyun#1]
-- 정리내용 -- 
1) 개발 환경 setup 에 대한 간단한 절차 작성
2) 파일 (입력 - 처리 - 결과) 에 대한 메모
3) 예제 파일을 이용한 실행 명령, command line 수행 방법

**Comment by jhyun0919** [comment]
제가 지금까지 봐왔던 github(Berepi,, EnerNOC vtn-ven, NILMTK etc) 참고하여 기본적인 틀 정도만 작성해놓았습니다,
앞으로 계속해서 관리해나가겠습니다.
가이드 라인 제공해 주셔서 감사합니다.

**Comment by jeonghoonkang** [comment]
한가지 빼 먹었는데. RAW 데이터를 그래프로 그리는 방법도 설명을 써주면 좋겠음.
